
const bouton = document.getElementById('validated');
bouton.addEventListener('click', check);

const res = document.getElementById('result');
const SCORE = document.getElementById('score');


let nb2 = Math.floor(Math.random() * 100) + 1;
console.log(nb2);

const phrases = [
    "Well done, honestly couldn't have done it, way stronger than me",
    "Wow i think u just FOUNNNNND ITTTTT well done",
    "Ain't no way u got this one.... gg",
    "U should get a life to be this good at it",
    "I'm impressed, u're a real one (generated by AI not even kidding)",
    "Marry me ? (not generated by AI)",
    "Be proud of stinking this much to play this game"
];

checkloc();


function checkloc() {
    if (localStorage.getItem('score') == null) {
        localStorage.setItem('score', 0);
    }
    SCORE.innerHTML += localStorage.getItem('score');
}


function addloc() {
    if (localStorage.getItem('score') == null) {
        localStorage.setItem('score', 0);
    } else {
        localStorage.setItem('score', parseInt(localStorage.getItem('score')) + 1);
    }
}


function check() {
    var nb = document.getElementById("myText").value;
    console.log(nb)
    if (nb2 == nb) {
        res.innerHTML = phrases[Math.floor(Math.random() * phrases.length)];
        addloc();
        setTimeout(function(){ window.location.reload(); }, 5000);
    } else if (nb2 < nb) {
        res.innerHTML = 'LOWER !';
        res.style.color = 'red'; 
    } else if (nb2 > nb) {
        res.innerHTML = 'HIGHER !';
        res.style.color = 'green'; 
    }
}


